/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTERFACE2_H_RPCGEN
#define _INTERFACE2_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 20
#define MAXAPEL 20

struct paciente_SA_SN {
	int numeroHabitacion;
	char nombre[MAXNOM];
	char apellido[MAXAPEL];
	int edad;
};
typedef struct paciente_SA_SN paciente_SA_SN;

struct indicadores_SA_SN {
	int frecuencia_cardiaca;
	int tension_arterial[2];
	int frecuencia_respiratoria;
	int saturacion_oxigeno;
	float temperatura;
};
typedef struct indicadores_SA_SN indicadores_SA_SN;

struct alerta {
	char horaAlerta[50];
	char fechaAlerta[50];
	int puntuacion;
};
typedef struct alerta alerta;

struct notificacion {
	char horaAlerta[50];
	char fechaAlerta[50];
	alerta vecUltimasAlertas[5];
	int cantidadAlertas;
	int puntuacion;
	indicadores_SA_SN objIndicadores;
	paciente_SA_SN objPaciente;
};
typedef struct notificacion notificacion;

#define enviar_notificacion 0x20000002
#define enviar_notificacion_1 2

#if defined(__STDC__) || defined(__cplusplus)
#define enviarNotificacion 1
extern  bool_t * enviarnotificacion_2(notificacion *, CLIENT *);
extern  bool_t * enviarnotificacion_2_svc(notificacion *, struct svc_req *);
extern int enviar_notificacion_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define enviarNotificacion 1
extern  bool_t * enviarnotificacion_2();
extern  bool_t * enviarnotificacion_2_svc();
extern int enviar_notificacion_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_paciente_SA_SN (XDR *, paciente_SA_SN*);
extern  bool_t xdr_indicadores_SA_SN (XDR *, indicadores_SA_SN*);
extern  bool_t xdr_alerta (XDR *, alerta*);
extern  bool_t xdr_notificacion (XDR *, notificacion*);

#else /* K&R C */
extern bool_t xdr_paciente_SA_SN ();
extern bool_t xdr_indicadores_SA_SN ();
extern bool_t xdr_alerta ();
extern bool_t xdr_notificacion ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTERFACE2_H_RPCGEN */
