/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface1.h"
#include <stdbool.h>
#include <unistd.h>

int generarValorSensor(int rangoInf, int ranfoSup){
	return rangoInf + rand() % (ranfoSup - rangoInf +1);
}

float generarValorTemperatura(float min, float max) {
  return (float)rand() / (float)RAND_MAX * (max - min) + min;
}

int validarEntrada(int numero, int minimo, int maximo) {
	// Validamos el número
	if (numero >= minimo && numero <= maximo) {
		// El número es válido, devolvemos 1
		return 1;
	} else {
		// El número no es válido, devolvemos 0
		return 0;
	}
}

void imprimirTitulo(char * titulo){
	printf("==================================\n");
	printf("===== %s =====\n", titulo);
	printf("==================================\n");
}

void imprimirMensajeEnvioDatos(paciente_C_SA * datosPaciente){
	printf("\nEnviando indicadores ...\n");
	printf("Frecuencia cardiaca: %d\n", datosPaciente->valoresPaciente.frecuencia_cardiaca);
	printf("Presión arterial: %d/%d\n", datosPaciente->valoresPaciente.tension_arterial[0], datosPaciente->valoresPaciente.tension_arterial[1]);
	printf("Frecuencia respiratoria: %d\n", datosPaciente->valoresPaciente.frecuencia_respiratoria);
	printf("Temperatura: %.2f\n", datosPaciente->valoresPaciente.temperatura);
	printf("Saturación de oxígeno: %d\n", datosPaciente->valoresPaciente.saturacion_oxigeno);
}

int generarFrecuenciaCardiaca(int edad){
	
	if(edad < 1){ //Infante y RN
		return generarValorSensor(100,140);
	}
	else if(edad >= 1 && edad < 2){ //Lactante mayor
		return generarValorSensor(100,200);
	}
	else if(edad >= 2 && edad < 6){ //Pre-escolar
		return generarValorSensor(80,120);
	}
	else if(edad >= 6 && edad < 13){ //Escolar
		return generarValorSensor(80,100);
	}
	else if(edad >= 13 && edad < 16){ //Adolescente
		return generarValorSensor(70,80);
	}
	else if(edad >= 16){ //Adulto
		return generarValorSensor(50,90); //Se aumenta el rango para que genere alertas
	}
}

void generarTensionArterial(int edad, int * vecTensiones){
	//Posicion 0 vecTension Sistólica
	//Posicion 1 vecTension Diastólica
	if(edad < 1){ //Infante y RN
		vecTensiones[0] = generarValorSensor(70,106); 
		vecTensiones[1] = generarValorSensor(50,70);
	}
	else if(edad >= 1 && edad <= 2){ //Lactante mayor
		vecTensiones[0] = generarValorSensor(98,106); 
		vecTensiones[1] = generarValorSensor(58,70);
	}
	else if(edad >= 2 && edad < 6){ //Pre-escolar
		vecTensiones[0] = generarValorSensor(99,112); 
		vecTensiones[1] = generarValorSensor(64,70);
	}
	else if(edad >= 6 && edad < 13){ //Escolar
		vecTensiones[0] = generarValorSensor(104,124); 
		vecTensiones[1] = generarValorSensor(64,86);
	}
	else if(edad >= 13 && edad < 16){ //Adolescente
		vecTensiones[0] = generarValorSensor(118,132); 
		vecTensiones[1] = generarValorSensor(70,82);
	}
	else if(edad >= 16){ //Adulto
		vecTensiones[0] = generarValorSensor(100,150); //Se aumenta el rango para que genere alertas
		vecTensiones[1] = generarValorSensor(60,100); //Se aumenta el rango para que genere alertas
	}
}

int generarFrecuenciaRespiratoria(int edad){
	
	if(edad < 1){ //Infante y RN
		return generarValorSensor(20,45);
	}
	else if(edad >= 1 && edad < 6){ //Lactante mayor y pre-escolar
		return generarValorSensor(20,30);
	}
	else if(edad >= 6){ //Escolar, adolescente y adulto
		return generarValorSensor(2,30); //Se aumenta el rango para que genere alertas
	}
}

int generarTemperatura(int edad){
	if(edad < 1){ //Infante y RN
		return generarValorTemperatura(37.5,38.0);
	}
	else if(edad >= 1 && edad < 6){ //Lactante mayor
		return generarValorTemperatura(37.5,37.8);
	}
	else if(edad >= 6 && edad < 13){ //Escolar
		return generarValorTemperatura(37.0,37.5);
	}
	else if(edad >= 13 && edad < 16){ //Adolescente
		return 37.0;
	}
	else if(edad >= 16){ //Adulto
		return generarValorTemperatura(35.2,40.2); //Se aumenta el rango para que genere alertas
	}
}

int generarSaturacionOxigeno(){
	return generarValorSensor(80,100); //Son porcentajes que se le pasan, es decir 86% y 100% //Se baja el rango minimo para que genere alertas
}

void comenzarLecturaSensores(paciente_C_SA * datosPaciente){
	int edad = datosPaciente->edad;

	imprimirTitulo("LECTURA DE SENSORES");
	datosPaciente->valoresPaciente.frecuencia_cardiaca = generarFrecuenciaCardiaca(edad);
	generarTensionArterial(edad, datosPaciente->valoresPaciente.tension_arterial);
	datosPaciente->valoresPaciente.frecuencia_respiratoria = generarFrecuenciaRespiratoria(edad);
	datosPaciente->valoresPaciente.temperatura = generarTemperatura(edad);
	datosPaciente->valoresPaciente.saturacion_oxigeno = generarSaturacionOxigeno();
}

void ingresarPaciente(paciente_C_SA * datosPaciente){
	
	imprimirTitulo("INGRESAR DATOS PACIENTES");

	do{
		printf("\n Ingrese el numero de habitacion: ");
		scanf("%d",&datosPaciente->numeroHabitacion);

		if(datosPaciente->numeroHabitacion < 100 || datosPaciente->numeroHabitacion > 999){
			printf("Error! El número de habitacion no puede ser menor que 100 o mayor a 999.\n");
		}
	}while(!validarEntrada(datosPaciente->numeroHabitacion, 100,999));

	printf("\n Ingrese el nombre: ");
	scanf("%s",datosPaciente->nombre);

	printf("\n Ingrese el apellido: ");
	scanf("%s",datosPaciente->apellido);

	do{
		printf("\n Ingrese la edad: ");
		scanf("%d",&datosPaciente->edad);

		if(datosPaciente->edad < 0){
			printf("Error! La edad no puede ser menor o igual que 0\n");
		}
	}while(datosPaciente->edad < 0);
}

void
enviar_datos_pacientes_2(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	paciente_C_SA  objDatosPaciente;

#ifndef	DEBUG
	clnt = clnt_create (host, enviar_datos_pacientes, enviar_datos_pacientes_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	int opcion = 0;
	do{
		printf("======= MENU DE SENSORES =======\n");
		printf("1.\t Ingresar datos del paciente\n");
		printf("2.\t Comenzar lectura de los sensores\n");
		printf("Ingrese una opción: ");
		scanf("%d", &opcion);

		switch(opcion){
			case 1:
				ingresarPaciente(&objDatosPaciente);
				break;
			case 2:
				while(true){
					comenzarLecturaSensores(&objDatosPaciente);
					imprimirMensajeEnvioDatos(&objDatosPaciente);
					result_1 = enviardatospacientes_2(&objDatosPaciente, clnt);
					if (result_1 == (bool_t *) NULL) {
						clnt_perror (clnt, "call failed");
					}
					sleep(8); //Esperará 8 segundos antes de la siguiente lectura y siguiente envío de datos al servidor
				}
				break;
			default:
				printf("Error! Esa opcion no es valida. Intentelo de nuevo");
				break;
		}
	}while(opcion!=2);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	enviar_datos_pacientes_2 (host);
exit (0);
}